### ISSUE TITLE
add_participants issue 

### ISSUE THREAD

**Issue by vikrampande7** [kartikrawool/expertiza#3]
CourseTeam and Course both have add_participants. Why?  If one of them is not used, remove it.  Should CourseTeam’s add_participant be called add_member?  Should it be in the Team superclass?

**Comment by kartikrawool** [comment]
Assignment_team and Course_team are subclasses of Team. Both should follow a similar logic for adding members of respective teams. Add_participants in both course and course_team have different applications; hence both should exist in the code. To make the code more consistent among the classes team, course_team, and assignment_team, the add_member function should be present only in the team class.
